template_path: bridgeserver2-https-redirect.yaml
stack_name: bridgeserver2-https-redirect-prod
dependencies:
  - prod/bridgeserver2.yaml
parameters:
  LoadBalancerArn: PLACEHOLDER_FILL_IN_AFTER_PHASE_7