template_path: bridgeserver2-https-redirect.yaml
stack_name: bridgeserver2-https-redirect-develop
depedencies:
  - develop/bridgeserver2.yaml
parameters:
  LoadBalancerArn: "arn:aws:elasticloadbalancing:us-east-1:433864969993:loadbalancer/app/gv-bridge-dev/5d7811896e0d8bc3"
