template_path: bridgeserver2-https-redirect.yaml
stack_name: bridgeserver2-https-redirect-uat
depedencies:
  - uat/bridgeserver2.yaml
parameters:
  LoadBalancerArn: "arn:aws:elasticloadbalancing:us-east-1:433864969993:loadbalancer/app/awseb--AWSEB-jlkPR3pHPO3w/bae888c80736abbc"
